In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
df = pd.read_csv('Shill Bidding Dataset.csv')

In [29]:
df.head()

Auction_ID  Bidder_Tendency  Bidding_Ratio  Successive_Outbidding  \
0         732         0.200000       0.400000                    0.0   
1         732         0.024390       0.200000                    0.0   
2         732         0.142857       0.200000                    0.0   
3         732         0.100000       0.200000                    0.0   
4         900         0.051282       0.222222                    0.0   

   Last_Bidding  Auction_Bids  Starting_Price_Average  Early_Bidding  \
0      0.000028           0.0                0.993593       0.000028   
1      0.013123           0.0                0.993593       0.013123   
2      0.003042           0.0                0.993593       0.003042   
3      0.097477           0.0                0.993593       0.097477   
4      0.001318           0.0                0.000000       0.001242   

   Winning_Ratio  Auction_Duration  Class  
0       0.666667                 5      0  
1       0.944444                 5      0  
2       1.000000                 5      0  
3       1.000000                 5      0  
4       0.500000                 7      0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6321 entries, 0 to 6320
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Record_ID               6321 non-null   int64  
 1   Auction_ID              6321 non-null   int64  
 2   Bidder_ID               6321 non-null   object 
 3   Bidder_Tendency         6321 non-null   float64
 4   Bidding_Ratio           6321 non-null   float64
 5   Successive_Outbidding   6321 non-null   float64
 6   Last_Bidding            6321 non-null   float64
 7   Auction_Bids            6321 non-null   float64
 8   Starting_Price_Average  6321 non-null   float64
 9   Early_Bidding           6321 non-null   float64
 10  Winning_Ratio           6321 non-null   float64
 11  Auction_Duration        6321 non-null   int64  
 12  Class                   6321 non-null   int64  
dtypes: float64(8), int64(4), object(1)
memory usage: 617.3+ KB


In [5]:
df['Auction_Duration'].value_counts()

7     2427
3     1408
1     1289
5     1060
10     137
Name: Auction_Duration, dtype: int64

In [6]:
df.columns

Index(['Record_ID', 'Auction_ID', 'Bidder_ID', 'Bidder_Tendency',
       'Bidding_Ratio', 'Successive_Outbidding', 'Last_Bidding',
       'Auction_Bids', 'Starting_Price_Average', 'Early_Bidding',
       'Winning_Ratio', 'Auction_Duration', 'Class'],
      dtype='object')

In [7]:
df.drop(['Record_ID', 'Bidder_ID'], axis = 1, inplace= True)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X = df.drop('Class', 1)
y = df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
scaler = MinMaxScaler()

In [12]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [14]:
X_train = scaler.transform(X_train)

In [15]:
X_test = scaler.transform(X_test)

In [20]:
y_test

4083    0
3844    0
712     0
3649    0
2873    0
       ..
4726    0
3816    0
4376    0
120     0
1777    1
Name: Class, Length: 2086, dtype: int64

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
log = LogisticRegression()

In [23]:
log.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
l_pred = log.predict(X_test)

In [25]:
from sklearn.metrics import classification_report, confusion_matrix

In [26]:
print(classification_report(y_test, l_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      1876
           1       0.83      0.91      0.87       210

    accuracy                           0.97      2086
   macro avg       0.91      0.95      0.93      2086
weighted avg       0.97      0.97      0.97      2086



In [27]:
print(confusion_matrix(y_test, l_pred))

[[1838   38]
 [  18  192]]


In [28]:
X_test.shape

(2086, 10)

In [84]:
new = scaler.transform(np.array([0,0.25,0.4,0,0.0015,1,0.993593,0.0014,0.667,50]).reshape(1,-1))

In [87]:
log.predict(new)

array([0], dtype=int64)

In [50]:
from sklearn.svm import SVC

In [51]:
svc = SVC()

In [52]:
from sklearn.model_selection import GridSearchCV

In [61]:
grid = GridSearchCV(estimator= SVC(), param_grid= param, verbose=1)

In [60]:
param = {'C':[0.1,1,10,100,1000], 'gamma':[1,0.1,0.001,0.0001,0.00001]}

In [62]:
grid.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 3 folds for each of 25 candidates, totalling 75 fits


[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed:   10.7s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.001, 0.0001, 1e-05]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=1)

In [63]:
grid.best_estimator_

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [64]:
svc = SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [65]:
svc.fit(X_train, y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [66]:
s_predict = svc.predict(X_test)

In [67]:
print(classification_report(y_test, s_predict))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      1876
           1       0.92      0.98      0.95       210

    accuracy                           0.99      2086
   macro avg       0.96      0.99      0.97      2086
weighted avg       0.99      0.99      0.99      2086



In [86]:
svc.predict(new)

array([1], dtype=int64)

In [88]:
import pickle

In [89]:
import joblib

In [90]:
filename = 'finalized_model.sav'

In [91]:
joblib.dump(s_predict, filename)

['finalized_model.sav']

In [92]:
joblib.load(filename)

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)